# **Exercise: Basics of Python and Numpy**

1. Import numpy and print the numpy version. (Hint: use ```__version___``` attribute to check package version.)

In [1]:
import numpy as np
np.__version__

'2.3.2'

2. Create a 4 x 5 matrix filled with random values. Name it as ```x```.

In [ ]:
x= np.random.random((4,5)) 
x

array([[0.20581483, 0.17914999, 0.37818263, 0.21586657, 0.3069738 ],
       [0.43503374, 0.40258056, 0.72131124, 0.79556406, 0.23543722],
       [0.94522351, 0.918648  , 0.92882613, 0.07689917, 0.34475966],
       [0.97822273, 0.96910789, 0.22894919, 0.55226863, 0.72126622]])

3. Create a 3 x 3 matrix filled with [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Name it as ```y```.

In [89]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

4. Swap the first two rows of ```x```.

In [98]:
x[[0,1],:]=x[[1,0],:]
x

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

5. Create a random numpy array with shape (100, 2) and name it ```z```. Each row indicates the coordinates of a point. Compute point by point distances.

In [ ]:
z= np.random.random([100,2])

## my way
distance1 = np.zeros((len(z), len(z)))
for i in range(len(z)):
    for j in range(len(z)):
        distance1[i, j] = np.linalg.norm(z[i]- z[j])


# ## copilot way
diff2 = z[:, None, :] - z[None, :, :]   
distance2 = np.linalg.norm(diff2, axis=-1)      

print(distance1)

print(distance1==distance2)


[[0.         0.48139795 0.38832001 ... 0.96046628 0.6987326  0.18680305]
 [0.48139795 0.         0.10106663 ... 0.48352852 0.29707494 0.43041027]
 [0.38832001 0.10106663 0.         ... 0.57215537 0.33849618 0.32945063]
 ...
 [0.96046628 0.48352852 0.57215537 ... 0.         0.33432798 0.87462356]
 [0.6987326  0.29707494 0.33849618 ... 0.33432798 0.         0.57632537]
 [0.18680305 0.43041027 0.32945063 ... 0.87462356 0.57632537 0.        ]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


6. Subtract the mean of each row of ```y```.

In [100]:
ysm = y - y.mean(axis=1, keepdims=True)
print(ysm)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


7. Add a vector [1, 0, 1] to each row of ```y``` using broadcasting and name the resulting numpy array as ```yy```.

In [101]:
v = np.array([1, 0, 1])
yy= y + v 

print(yy)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


8. For each row in ```yy```, extract the value that are not equal to the other two values. Organize these values as a numpy array.

In [114]:
eq1= yy[:, 0] == yy[:, 1]
eq2 = yy[:, 0] == yy[:, 2]

idx = np.where(eq1, 2, np.where(eq2, 1, 0))

notEq = yy[np.arange(yy.shape[0]), idx]
notEq

array([ 4,  7, 10])